
language: java

sudo: false

dist: trusty

jdk:
  - openjdk9

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - true
  
script:
  - mvn -Dmaven.test.skip=true clean package
  - mvn -Dmaven.test.skip=true -Dgpg.skip=true -DcreateChecksum=true install

deploy:
  provider: releases
  api_key:
    secure: xYu1oy9u9+GhEIot3D0bRGZh2s2v8neuk3YWRrh/ZuV4IOiuOGWV3CFr4ujIeNV/DBHSIwnEfPM+8NOGCOYE0uEK0kJomNeUQMrQW6+hEzacIwVjQ7AwYM1YwsR/J8dBIJj+BU3jBOthQESX9CTfU6aqA988AugRlaMPApjk2GxE1XwODW6HWRarLiD+u2ucBcSUjN5L3chJooVxO2gmA5f39XPilTiKSjgNattsUzPWu2ar4ZyB4PBJRdkG7ZqEEPP0YCTn/om6+rsOuf/H3P5UEpkHcEWSsxRs97SvVDOp4Cb1UOP8NbTr+Erx9WFF4VnIY1Hl05N4+fVdO+DppQ39oGpjNWvAB8F2M4oXh73dPdOKvjk56U1T4N533LmhAiOd1AsOkT80t43miRTR/YS8LrHoo39j2Iji7w8Ppr8tEeMFZmLYp6QTjEMPmn5n+CrJzn7swGUIjVJSOWKSCZlNcrsVyr/v1Lyu+qSz2NFRDky0DzUJsPDsyPj7S4ggKjcVPDavq3xT38zdd8VgbSgrjLizaW1MFJK1AyW/6GIbBy04YD8RT4tYwbdFR58qdRnvzAdRnn4i9XaW/SFdOwL0qnFID62T53XumJcBrWqSZzASBupiPPLMqy/cTP95FygZ1w9veenb0N3HYmMZ+EhNkQ7ZFq9HdPj2sidI5VM=
  file_glob: true
  file:
    - $HOME/.m2/repository/org/robotframework/remoteswinglibrary/*/remoteswinglibrary-*.*.sha1
    - $HOME/.m2/repository/org/robotframework/remoteswinglibrary/*/remoteswinglibrary-*.pom
    - $HOME/.m2/repository/org/robotframework/remoteswinglibrary/*/remoteswinglibrary-*.jar
  skip_cleanup: true
  overwrite: true
  on:
    repo: madworx/remoteswinglibrary
    tags: true
